'use strict';

// WhatsApp Flows endpoint encryption.
//
// Meta encrypts the request body with a hybrid scheme and expects the
// response encrypted the same way:
//   1. A fresh AES key is generated by the client per request and
//      RSA-encrypted (RSA-OAEP, SHA-256) with OUR public key. We decrypt
//      it with our private key.
//   2. The flow data JSON is AES-GCM encrypted with that key + a 16-byte
//      initialization vector. The GCM auth tag (16 bytes) is appended to
//      the ciphertext.
//   3. For the response we reuse the SAME AES key, but with the IV
//      BITWISE-INVERTED (each byte XOR 0xFF) — this is a hard requirement
//      from Meta; reusing the IV as-is is rejected.
//
// Request body shape (base64 fields):
//   { encrypted_flow_data, encrypted_aes_key, initial_vector }
//
// Response: a bare base64 string (NOT JSON) — the AES-GCM ciphertext of
// our JSON response, tag appended, encrypted under the flipped IV.
//
// Docs: https://developers.facebook.com/docs/whatsapp/flows/reference/implementingyourflowendpoint

const crypto = require('crypto');
const { logger } = require('../utils/logger');

const TAG_LENGTH = 16; // AES-GCM auth tag, bytes

/**
 * Load the RSA private key (PEM) from env. Supports either a raw PEM with
 * real newlines or a single-line PEM with literal "\n" escapes (common
 * when storing multi-line secrets in a .env / dashboard).
 *
 * Optional passphrase via FLOW_PRIVATE_KEY_PASSPHRASE (set if the key was
 * generated with -des3 like the spec's openssl command).
 */
function loadPrivateKey() {
  // Preferred: base64-encoded PEM in WHATSAPP_FLOW_PRIVATE_KEY_B64. A single
  // base64 token has no newlines/quotes for an env-var UI (Render, etc.) to
  // mangle — the \n-escaped form keeps getting corrupted on paste. Decode
  // it back to a normal multi-line PEM.
  const b64 = (process.env.WHATSAPP_FLOW_PRIVATE_KEY_B64 || process.env.FLOW_PRIVATE_KEY_B64 || '').trim();
  if (b64) {
    const decoded = Buffer.from(b64.replace(/\s+/g, ''), 'base64').toString('utf8');
    const passphraseB = process.env.WHATSAPP_FLOW_PRIVATE_KEY_PASSPHRASE
      || process.env.FLOW_PRIVATE_KEY_PASSPHRASE || undefined;
    return passphraseB ? { key: decoded, passphrase: passphraseB } : decoded;
  }

  let pem = process.env.WHATSAPP_FLOW_PRIVATE_KEY || process.env.FLOW_PRIVATE_KEY || '';
  if (!pem) throw new Error('WHATSAPP_FLOW_PRIVATE_KEY_B64 / WHATSAPP_FLOW_PRIVATE_KEY not set');
  pem = pem.trim();
  // Strip an accidental KEY= prefix (pasting the whole .env line).
  pem = pem.replace(/^WHATSAPP_FLOW_PRIVATE_KEY\s*=\s*/, '');
  // Strip wrapping quotes — the .env single-line form is quoted, but pasting
  // that quoted value straight into a dashboard env field (Render, etc.)
  // keeps the quotes, leaving a stray " inside the PEM → decrypt failure.
  if ((pem.startsWith('"') && pem.endsWith('"')) || (pem.startsWith("'") && pem.endsWith("'"))) {
    pem = pem.slice(1, -1);
  }
  // Normalize escaped newlines to real ones.
  if (pem.includes('\\n')) pem = pem.replace(/\\n/g, '\n');
  const passphrase = process.env.WHATSAPP_FLOW_PRIVATE_KEY_PASSPHRASE
    || process.env.FLOW_PRIVATE_KEY_PASSPHRASE
    || undefined;
  return passphrase ? { key: pem, passphrase } : pem;
}

/**
 * Decrypt an inbound Flow request.
 *
 * @param {{encrypted_flow_data:string, encrypted_aes_key:string, initial_vector:string}} body
 * @param {string|object} [privateKey] override (mainly for tests)
 * @returns {{ decrypted: object, aesKeyBuffer: Buffer, initialVectorBuffer: Buffer }}
 */
function decryptRequest(body, privateKey) {
  const { encrypted_flow_data, encrypted_aes_key, initial_vector } = body || {};
  if (!encrypted_flow_data || !encrypted_aes_key || !initial_vector) {
    throw new Error('Missing encrypted fields in Flow request body');
  }

  const key = privateKey || loadPrivateKey();

  // 1. RSA-OAEP(SHA-256) decrypt the AES key.
  let aesKeyBuffer;
  try {
    aesKeyBuffer = crypto.privateDecrypt(
      {
        key,
        padding: crypto.constants.RSA_PKCS1_OAEP_PADDING,
        oaepHash: 'sha256',
      },
      Buffer.from(encrypted_aes_key, 'base64')
    );
  } catch (err) {
    // Meta wants a 421 on a key-mismatch so it re-fetches our public key.
    const e = new Error(`Failed to RSA-decrypt AES key: ${err.message}`);
    e.code = 'FLOW_KEY_DECRYPT_FAILED';
    throw e;
  }

  // 2. AES-GCM decrypt the flow data. Cipher is GCM(keyLen*8). The tag is
  //    the last 16 bytes of the ciphertext.
  const ivBuffer = Buffer.from(initial_vector, 'base64');
  const flowDataBuffer = Buffer.from(encrypted_flow_data, 'base64');
  const tag = flowDataBuffer.subarray(flowDataBuffer.length - TAG_LENGTH);
  const ciphertext = flowDataBuffer.subarray(0, flowDataBuffer.length - TAG_LENGTH);

  const algorithm = `aes-${aesKeyBuffer.length * 8}-gcm`; // aes-128-gcm or aes-256-gcm
  const decipher = crypto.createDecipheriv(algorithm, aesKeyBuffer, ivBuffer);
  decipher.setAuthTag(tag);

  const decryptedRaw = Buffer.concat([decipher.update(ciphertext), decipher.final()]);
  let decrypted;
  try {
    decrypted = JSON.parse(decryptedRaw.toString('utf8'));
  } catch (err) {
    throw new Error(`Flow data decrypted but is not valid JSON: ${err.message}`);
  }

  return { decrypted, aesKeyBuffer, initialVectorBuffer: ivBuffer };
}

/**
 * Encrypt the response object. Reuses the request's AES key with the IV
 * bit-inverted. Returns a bare base64 string (the body to send back with
 * Content-Type: text/plain).
 *
 * @param {object} responseObj
 * @param {Buffer} aesKeyBuffer
 * @param {Buffer} initialVectorBuffer
 * @returns {string} base64
 */
function encryptResponse(responseObj, aesKeyBuffer, initialVectorBuffer) {
  // Flip every bit of the IV (XOR 0xFF) — Meta requirement.
  const flippedIv = Buffer.from(initialVectorBuffer.map((b) => b ^ 0xff));

  const algorithm = `aes-${aesKeyBuffer.length * 8}-gcm`;
  const cipher = crypto.createCipheriv(algorithm, aesKeyBuffer, flippedIv);

  const encrypted = Buffer.concat([
    cipher.update(JSON.stringify(responseObj), 'utf8'),
    cipher.final(),
  ]);
  const tag = cipher.getAuthTag();

  // Ciphertext + auth tag, base64-encoded.
  return Buffer.concat([encrypted, tag]).toString('base64');
}

/**
 * Convenience self-test used by the local test harness: encrypts a payload
 * the way Meta's client would (RSA-OAEP the AES key with the PUBLIC key,
 * AES-GCM the data) so decryptRequest can be exercised without Meta.
 *
 * @param {object} payload
 * @param {string} publicKeyPem
 * @returns {{encrypted_flow_data, encrypted_aes_key, initial_vector, _aesKey, _iv}}
 */
function _simulateClientEncrypt(payload, publicKeyPem) {
  const aesKey = crypto.randomBytes(16); // 128-bit, like Meta's client
  const iv = crypto.randomBytes(16);

  const cipher = crypto.createCipheriv('aes-128-gcm', aesKey, iv);
  const enc = Buffer.concat([cipher.update(JSON.stringify(payload), 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();

  const encryptedAesKey = crypto.publicEncrypt(
    { key: publicKeyPem, padding: crypto.constants.RSA_PKCS1_OAEP_PADDING, oaepHash: 'sha256' },
    aesKey
  );

  return {
    encrypted_flow_data: Buffer.concat([enc, tag]).toString('base64'),
    encrypted_aes_key: encryptedAesKey.toString('base64'),
    initial_vector: iv.toString('base64'),
    _aesKey: aesKey,
    _iv: iv,
  };
}

module.exports = {
  decryptRequest,
  encryptResponse,
  loadPrivateKey,
  _simulateClientEncrypt,
};
