// AUTO-GENERATED by scripts/generateDemoSites.js — do not edit by hand.
// Run `node scripts/generateDemoSites.js` to regenerate the sites and
// update this file with fresh Netlify preview URLs.

export interface DemoSite {
  id: string;
  label: string;
  businessName: string;
  industry: string;
  city: string;
  prompt: string;
  url: string;
}

export const DEMO_SITES: DemoSite[] = [
  {
    "id": "hvac",
    "label": "HVAC",
    "prompt": "I need a website for my HVAC company in Austin. We do AC repair, heating, duct cleaning, and emergency service.",
    "businessName": "Austin Climate Pros",
    "industry": "HVAC",
    "city": "Austin, TX",
    "url": "https://austinclimate.pixiebot.co"
  },
  {
    "id": "real-estate",
    "label": "Real Estate",
    "prompt": "I'm a realtor in Austin. I work with luxury buyers and first-time homeowners across Westlake, Circle C, and Barton Hills.",
    "businessName": "Sarah Mitchell",
    "industry": "Real Estate",
    "city": "Austin, TX",
    "url": "https://sarahmitchell.pixiebot.co"
  },
  {
    "id": "salon",
    "label": "Salon",
    "prompt": "I run a hair salon in Miami Beach. I need a website with online booking, an Instagram feed, and pricing for cuts and color.",
    "businessName": "Blush Bar",
    "industry": "Hair Salon",
    "city": "Miami Beach, FL",
    "url": "https://blushbar.pixiebot.co"
  },
  {
    "id": "generic",
    "label": "Coffee Shop",
    "prompt": "I own a specialty coffee shop in Portland. I want a clean site with our drinks, wholesale beans, and contact info.",
    "businessName": "Byte Coffee Co.",
    "industry": "Specialty coffee shop",
    "city": "Portland, OR",
    "url": "https://bytecoffee.pixiebot.co"
  },
  {
    "id": "developer",
    "label": "Developer",
    "prompt": "I'm a full-stack engineer in Berlin. I want a portfolio site to show my projects, my stack, and an easy way for companies to reach me.",
    "businessName": "Alex Rivera",
    "industry": "Developer portfolio",
    "city": "Berlin",
    "url": "https://alexrivera.pixiebot.co"
  },
  {
    "id": "photographer",
    "label": "Photographer",
    "prompt": "I'm a wedding & portrait photographer in San Francisco. I want a portfolio site for my galleries, my story, and a way for couples to enquire about dates.",
    "businessName": "Hana Lee",
    "industry": "Photography portfolio",
    "city": "San Francisco",
    "url": "https://hana.pixiebot.co"
  },
  {
    "id": "designer",
    "label": "Designer",
    "prompt": "I'm a graphic & poster designer in London. I want a portfolio site for my posters, my process, and an easy way for clients to reach me.",
    "businessName": "Eleanor Hartley",
    "industry": "Graphic & Poster Designer",
    "city": "London",
    "url": "https://eleanor.pixiebot.co"
  }
];