#!/usr/bin/env node
/**
 * Generate + deploy the demo sites used by pixiebot.co/examples.
 * Most are built from scratch through the real generator + deployer; demos
 * flagged `static: true` (e.g. the developer portfolio) are curated and pass
 * straight through to demoSites.ts without being rebuilt.
 *
 * Run from repo root:
 *   node scripts/generateDemoSites.js
 *
 * Requires the usual env vars: NETLIFY_TOKEN, UNSPLASH_ACCESS_KEY,
 * OPENAI_API_KEY / ANTHROPIC_API_KEY. Each fixture goes through the
 * real generator + deployer — the output is indistinguishable from a
 * customer site. Results are written to landing/lib/demoSites.ts so
 * the Examples page can import them.
 */

const fs = require('fs');
const path = require('path');

// Load env before anything else
require('dotenv').config();

const { generateWebsiteContent } = require('../src/website-gen/generator');
const { deployToNetlify } = require('../src/website-gen/deployer');
const { logger } = require('../src/utils/logger');

const DEMOS = [
  require('./demos/hvacDemo'),
  require('./demos/realEstateDemo'),
  require('./demos/salonDemo'),
  require('./demos/genericDemo'),
  require('./demos/developerDemo'), // static — curated, not rebuilt
  require('./demos/photographerDemo'), // static — curated, not rebuilt
  require('./demos/designerDemo'), // static — curated, not rebuilt
];

async function buildOne(demo) {
  const { id, label, prompt, templateId, businessData } = demo;

  // Static (curated) demos — e.g. the hand-built developer portfolio — are not
  // regenerated. Their fields pass straight through to demoSites.ts so a
  // regen run can't replace a bespoke preview with a generic template render.
  if (demo.static) {
    console.log(`\n━━━ Static ${label} (${id}) — curated, not rebuilt ━━━`);
    console.log(`  [url]     ${demo.url}`);
    return {
      id,
      label,
      prompt,
      businessName: demo.businessName,
      industry: demo.industry,
      city: demo.city,
      url: demo.url,
    };
  }

  console.log(`\n━━━ Building ${label} (${id}) ━━━`);

  const extras = {};
  if (templateId) extras.templateId = templateId;

  const t0 = Date.now();
  const siteConfig = await generateWebsiteContent(businessData, extras);
  console.log(`  [content] done in ${Math.round((Date.now() - t0) / 1000)}s`);

  const t1 = Date.now();
  const { previewUrl, netlifySiteId } = await deployToNetlify(siteConfig);
  console.log(`  [deploy]  done in ${Math.round((Date.now() - t1) / 1000)}s`);
  console.log(`  [url]     ${previewUrl}`);

  return {
    id,
    label,
    prompt,
    businessName: businessData.businessName,
    industry: businessData.industry,
    city: businessData.primaryCity || extractCityFromAddress(businessData.contactAddress),
    url: previewUrl,
    netlifySiteId,
  };
}

function extractCityFromAddress(addr) {
  if (!addr) return '';
  // "1802 NW 23rd Ave, Portland, OR 97210" → "Portland, OR"
  const parts = String(addr).split(',').map((s) => s.trim());
  if (parts.length >= 3) return `${parts[parts.length - 2]}, ${parts[parts.length - 1].split(' ')[0]}`;
  return parts[parts.length - 1] || '';
}

function writeDemoSitesConfig(results) {
  const outPath = path.resolve(__dirname, '..', 'landing', 'lib', 'demoSites.ts');
  const body = `// AUTO-GENERATED by scripts/generateDemoSites.js — do not edit by hand.
// Run \`node scripts/generateDemoSites.js\` to regenerate the sites and
// update this file with fresh Netlify preview URLs.

export interface DemoSite {
  id: string;
  label: string;
  businessName: string;
  industry: string;
  city: string;
  prompt: string;
  url: string;
}

export const DEMO_SITES: DemoSite[] = ${JSON.stringify(
    results.map(({ netlifySiteId, ...rest }) => rest),
    null,
    2
  )};
`;
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, body);
  console.log(`\n✔ Wrote ${results.length} demo sites to ${path.relative(process.cwd(), outPath)}`);
}

async function main() {
  const results = [];
  const failures = [];

  for (const demo of DEMOS) {
    try {
      const r = await buildOne(demo);
      results.push(r);
    } catch (err) {
      console.error(`✗ ${demo.label} failed: ${err.message}`);
      logger.error?.(`[DEMO] ${demo.id} failed:`, err);
      failures.push({ id: demo.id, error: err.message });
    }
  }

  console.log('\n━━━ Summary ━━━');
  console.log(`  ✔ built : ${results.length}`);
  console.log(`  ✗ failed: ${failures.length}`);
  if (failures.length) {
    for (const f of failures) console.log(`    - ${f.id}: ${f.error}`);
  }

  if (results.length) writeDemoSitesConfig(results);
  process.exit(failures.length ? 1 : 0);
}

main().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
